fnm ="Asma";
lnm ="Banu";
console.log(fnm+" "+lnm);
console.log(fnm.length);
console.log(fnm.substr(3,4));
console.log(fnm.substring(1,2));
console.log(fnm.charAt(4));
console.log(fnm.indexOf('s'));
console.log(fnm.indexOf('B'));
console.log(fnm.toUpperCase());
console.log(fnm.toLowerCase());
console.log(fnm);